site_name: Whealthy
theme:
  name: material
plugins:
  - search
  - i18n:
      default_language: en
      languages:
        fr: Français
        en: English
nav:
  - Accueil: index.md
  - Architecture: architecture.md
  - API:
      - Auth: api/auth.md
      - Transactions: api/transactions.md
  - Développement:
      - Setup: dev/setup.md
      - Docker: dev/docker.md